// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARDCCzAnNc5LC44VNCtHIfnLTfeuQ_VSQ',
    appId: '1:546342052074:web:de4cc6f40494e6acd97793',
    messagingSenderId: '546342052074',
    projectId: 'recetario-43464',
    authDomain: 'recetario-43464.firebaseapp.com',
    storageBucket: 'recetario-43464.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmYPolPt6ABOwCG0BbRQnJ5CpBZbSzAwQ',
    appId: '1:546342052074:android:36e5053a9f111360d97793',
    messagingSenderId: '546342052074',
    projectId: 'recetario-43464',
    storageBucket: 'recetario-43464.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARDCCzAnNc5LC44VNCtHIfnLTfeuQ_VSQ',
    appId: '1:546342052074:web:329448fa0a6d9c4cd97793',
    messagingSenderId: '546342052074',
    projectId: 'recetario-43464',
    authDomain: 'recetario-43464.firebaseapp.com',
    storageBucket: 'recetario-43464.firebasestorage.app',
  );
}
